/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntek_rockchip_jni_RKJNI */

#ifndef _Included_com_ntek_rockchip_jni_RKJNI
#define _Included_com_ntek_rockchip_jni_RKJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    SEledlight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_SEledlight
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    SEledlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_SEledlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    SEledunlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_SEledunlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    SEledonline
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_SEledonline
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    SEledflash1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_SEledflash1
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    SEledflash2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_SEledflash2
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    SEledflashboth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_SEledflashboth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DPledspeaker
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DPledspeaker
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DPled1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DPled1
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DPled2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DPled2
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DT2led
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DT2led
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DT2Relay0Status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ntek_rockchip_jni_RKJNI_DT2Relay0Status
  (JNIEnv *, jobject);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DT2Relay1Status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ntek_rockchip_jni_RKJNI_DT2Relay1Status
  (JNIEnv *, jobject);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DT2MotionSensitivity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DT2MotionSensitivity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DT2Sensor0Sensitivity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DT2Sensor0Sensitivity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DT2Sensor1Sensitivity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DT2Sensor1Sensitivity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DT2DarknessLevel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DT2DarknessLevel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DT2IRSetLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DT2IRSetLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DPspeakerMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DPspeakerMode
  (JNIEnv *, jobject);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DPhandsetMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DPhandsetMode
  (JNIEnv *, jobject);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DPled1blink
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DPled1blink
  (JNIEnv *, jobject);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    DPled2blink
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_DPled2blink
  (JNIEnv *, jobject);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    relay0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_relay0
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    relay1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_relay1
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ntek_rockchip_jni_RKJNI
 * Method:    device
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ntek_rockchip_jni_RKJNI_device
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
