/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntek_doortalk2_led_Doortalkled */

#ifndef _Included_com_ntek_doortalk2_led_Doortalkled
#define _Included_com_ntek_doortalk2_led_Doortalkled
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntek_doortalk2_led_Doortalkled
 * Method:    setButtonLED
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ntek_doortalk2_led_Doortalkled_setButtonLED
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
